# Generated by Django 5.0 on 2023-12-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
