# Generated by Django 5.0 on 2023-12-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_watchlist', to='auctions.auctionlisting'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_watchlist'),
        ),
    ]
