# Generated by Django 5.0 on 2023-12-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_watchlist_product_watchlist_unique_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder_id',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='product_id',
            new_name='product',
        ),
    ]
