# Generated by Django 5.0 on 2023-12-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_bidder_id_bid_bidder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
    ]
